import { describe, expect, it } from 'vitest'
import { assertionById, assertions, basisMatches, comparisonRows, connections, exportInvestigation, findPaths, newInvestigation, objectById, objects, readInvestigations, searchObjects } from './workspace'

describe('investigation workspace',()=>{
 it('indexes every object and every assertion endpoint uniquely',()=>{expect(new Set(objects.map(x=>x.id)).size).toBe(objects.length);expect(new Set(assertions.map(x=>x.id)).size).toBe(assertions.length);for(const a of assertions){expect(objectById.has(a.sourceNodeId),a.id).toBe(true);expect(objectById.has(a.targetNodeId),a.id).toBe(true)}})
 it('searches provision detail as well as concepts and instruments',()=>{expect(searchObjects('GOVERN 3.2').some(x=>x.id==='provision:nist-govern-3-2')).toBe(true);expect(searchObjects('oversight','Concept').some(x=>x.id==='concept:human-oversight')).toBe(true);expect(searchObjects('zz-no-such-record')).toEqual([])})
 it('finds bounded real paths with exact directions retained on each assertion',()=>{const paths=findPaths('concept:human-oversight','control-objective:agent-runtime-constraints');expect(paths.length).toBeGreaterThan(0);for(const p of paths){expect(new Set(p.nodeIds).size).toBe(p.nodeIds.length);expect(p.edgeIds.length).toBeLessThanOrEqual(4);p.edgeIds.forEach((id,i)=>{const a=assertionById.get(id)!;expect([a.sourceNodeId,a.targetNodeId].sort()).toEqual([p.nodeIds[i],p.nodeIds[i+1]].sort())})}})
 it('does not turn shared editorial themes into semantic shortcuts',()=>{const p=findPaths('concept:privacy','concept:data-governance','all',2);for(const route of p)expect(route.nodeIds.slice(1,-1).some(id=>id.startsWith('domain:'))).toBe(false)})
 it('preserves source-only filtering and no-path conditions',()=>{expect(findPaths('concept:human-oversight','control-objective:agent-runtime-constraints','source-authored')).toEqual([]);expect(findPaths('invalid:x','concept:privacy')).toEqual([]);expect(findPaths('concept:privacy','concept:privacy')).toEqual([]);for(const a of connections('instrument:apra-cps-230','source-authored'))expect(basisMatches(a,'source-authored')).toBe(true)})
 it('retains precise provisions and missing-record distinctions in comparisons',()=>{const rows=comparisonRows(['apra-cps-230','nist-ai-rmf']);const oversight=rows.find(x=>x.concept.id==='human-oversight')!;expect(oversight.cells.find(x=>x.instrument.id==='apra-cps-230')?.recorded).toBe(false);expect(oversight.cells.find(x=>x.instrument.id==='nist-ai-rmf')?.provisions.some(p=>p.id==='nist-govern-3-2')).toBe(true)})
 it('exports routes, source citations, observations and limits separately',()=>{const item=newInvestigation('Oversight inquiry');item.question='Who can stop it?';item.notes='Needs owner review';item.paths=findPaths('concept:human-oversight','control-objective:agent-runtime-constraints').slice(0,1);item.nodeIds=item.paths[0].nodeIds;const output=exportInvestigation(item);expect(output).toContain('Who can stop it?');expect(output).toContain('## Personal observations');expect(output).toContain('Atlas interpretation');expect(output).toContain('https://');expect(output).toContain('not causal chains or compliance findings')})
 it('recovers valid investigations and safely handles corrupt storage',()=>{expect(readInvestigations('bad JSON')).toEqual([]);expect(readInvestigations('{"id":3}')).toEqual([]);const item=newInvestigation();item.nodeIds=['concept:privacy','invalid:node'];const [restored]=readInvestigations(JSON.stringify([item]));expect(restored.nodeIds).toEqual(['concept:privacy']);expect(restored.id).toBe(item.id)})
})
