import { ArrowRight, ArrowSquareOut, BookmarkSimple, GitBranch, X } from '@phosphor-icons/react'
import { useState } from 'react'
import { assertions, assertionById, basisLabel, connections, objectById, otherEnd, type BasisFilter } from '../lib/workspace'
import { instruments } from '../data/instruments'
import { controlObjectives } from '../data/controls'
import { riskSubdomains } from '../data/mitRiskTaxonomy'
import { authorityLabels } from '../lib/labels'
import type { MappingAssertion } from '../types'

type Props={selected:string;edge?:string;basis:BasisFilter;onSelect:(id:string)=>void;onEdge:(id?:string)=>void;onSave:()=>void;onTrace:()=>void;onCompare:(id:string)=>void;saved:boolean;onClose:()=>void}
export function CitationList({edge}:{edge:MappingAssertion}){return <div className="citation-list">{edge.citations.length?edge.citations.map((c,i)=><a key={`${c.url}-${i}`} href={c.url} target="_blank" rel="noreferrer"><ArrowSquareOut/><span><strong>{c.sourceTitle}</strong><small>{c.locator}</small><small>Accessed {c.accessedAt}{c.sourceVersion?` · ${c.sourceVersion}`:''}</small></span></a>):<p>No source citation recorded. This is an editorial navigation relationship.</p>}</div>}
export function EvidencePanel({selected,edge,basis,onSelect,onEdge,onSave,onTrace,onCompare,saved,onClose}:Props){
 const [tab,setTab]=useState('Overview');const x=objectById.get(selected)!;const a=edge?assertionById.get(edge):undefined
 const related=connections(selected,basis);const instrument=instruments.find(i=>i.id===x.sourceId);const provision=selected.startsWith('provision:')?instrument?.provisions.find(p=>`provision:${p.id}`===selected):undefined;const control=controlObjectives.find(c=>`control-objective:${c.id}`===selected);const risk=riskSubdomains.find(r=>`risk-subdomain:${r.id}`===selected)
 const sourceCount=related.filter(a=>a.basis==='source-authored').length,interpretationCount=related.filter(a=>a.basis==='atlas-synthesis').length
 return <aside className="evidence-panel" aria-label="Evidence inspector"><header><span>{a?'RELATIONSHIP RECORD':'OBJECT RECORD'}</span><button onClick={onClose} aria-label="Close evidence inspector"><X/></button></header>
 {a?<><button className="text-button" onClick={()=>onEdge(undefined)}>← Back to object</button><div className="edge-direction"><button onClick={()=>onSelect(a.sourceNodeId)}>{objectById.get(a.sourceNodeId)?.name}</button><span><ArrowRight/> {a.predicate.replaceAll('-',' ')}</span><button onClick={()=>onSelect(a.targetNodeId)}>{objectById.get(a.targetNodeId)?.name}</button></div><span className={`basis-pill ${a.basis}`}>{basisLabel[a.basis]}</span><h2>Why this connection exists</h2><p className="record-description">{a.rationale}</p><dl className="record-meta"><div><dt>Mapping confidence</dt><dd>{a.confidence} · not an assurance rating</dd></div><div><dt>Reviewed</dt><dd>{a.verifiedAt}</dd></div><div><dt>Inference depth</dt><dd>{a.inferenceDepth} · individual assertion</dd></div><div><dt>Status</dt><dd>{a.status}</dd></div></dl><button className="panel-primary" onClick={onSave}><BookmarkSimple/> {saved?'Saved to investigation':'Save relationship'}</button><h3>Source foundations</h3><CitationList edge={a}/><div className="record-limit">An arrow records this predicate in this direction. Following it backwards does not reverse the assertion. No competing interpretation is recorded; that does not establish consensus.</div></>:<>
 <div className="record-kind" style={{color:x.color}}>{x.kind} · {x.group}</div><h2>{x.name}</h2><p className="record-description">{x.summary}</p><div className="record-actions"><button onClick={onSave}><BookmarkSimple weight={saved?'fill':'regular'}/>{saved?'Saved':'Save'}</button><button onClick={onTrace}><GitBranch/> Find a path</button>{x.kind==='Source'&&<button onClick={()=>onCompare(x.sourceId!)}>Compare</button>}</div>
 <div className="record-counts"><span><strong>{sourceCount}</strong> source-authored</span><span><strong>{interpretationCount}</strong> interpretations</span></div>
 <nav className="record-tabs" aria-label="Inspector views">{['Overview','Connections','Sources'].map(t=><button key={t} aria-pressed={t===tab} onClick={()=>setTab(t)}>{t}{t==='Connections'?` ${related.length}`:''}</button>)}</nav>
 {tab==='Overview'&&<>
 {instrument&&<><dl className="record-meta"><div><dt>Authority</dt><dd>{authorityLabels[instrument.authorityClass]}</dd></div><div><dt>Context</dt><dd>{instrument.jurisdiction}</dd></div><div><dt>Source record reviewed</dt><dd>{provision?.reviewedAt??instrument.lastVerified}</dd></div><div><dt>Text access</dt><dd>{instrument.detailAvailability==='licensed-standard'?'Licensed standard · Atlas summaries only':instrument.detailAvailability==='public-summary'?'Public summary':'Full source publicly available'}</dd></div></dl><div className="record-limit"><strong>Partial corpus extraction</strong><p>{instrument.provisions.length} selected provision records; the Atlas does not reproduce or exhaustively map the instrument.</p>{provision?.note&&<p>{provision.note}</p>}</div><h3>Scope stated in the corpus</h3><p>{instrument.applicability}</p><a className="official-source" href={provision?.sourceUrl??instrument.officialUrl} target="_blank" rel="noreferrer">Read official source <ArrowSquareOut/></a>{!provision&&<><h3>Selected provisions</h3>{instrument.provisions.map(p=><button className="related-object" key={p.id} onClick={()=>onSelect(`provision:${p.id}`)}><span><small>{p.ref}{p.reviewedAt?` · checked ${p.reviewedAt}`:''}</small><strong>{p.title}</strong><p>{p.summary}</p></span><ArrowRight/></button>)}</> }</>}
 {control&&<><h3>Intended mechanism</h3><p>{control.purpose}</p><h3>Implementation examples</h3><ul>{control.implementationExamples.map(e=><li key={e}>{e}</li>)}</ul><h3>Evidence to request</h3><p className="subtle">Examples to investigate, not proof of implementation.</p><ul>{control.evidenceExamples.map(e=><li key={e}>{e}</li>)}</ul><h3>Questions for assessment</h3><ul><li>Who owns this control and its exceptions?</li><li>What demonstrates operation over the relevant period?</li><li>What failed, and how were failures resolved?</li></ul><h3>Risks this may address</h3>{control.riskIds.map(id=><button key={id} className="related-object" onClick={()=>onSelect(`risk-subdomain:${id}`)}>{objectById.get(`risk-subdomain:${id}`)?.name}<ArrowRight/></button>)}<div className="record-limit">Candidate response. Design, implementation and operating effectiveness require separate organisational evidence and human assessment.</div></>}
 {risk&&<><h3>What may be affected</h3>{risk.conceptIds.map(id=><button key={id} className="related-object" onClick={()=>onSelect(`concept:${id}`)}>{objectById.get(`concept:${id}`)?.name}<ArrowRight/></button>)}<h3>Candidate control responses</h3>{controlObjectives.filter(c=>c.riskIds.includes(risk.id)).map(c=><button className="related-object" key={c.id} onClick={()=>onSelect(`control-objective:${c.id}`)}><span><small>{c.code} · may address</small><strong>{c.name}</strong></span><ArrowRight/></button>)}<div className="record-limit">MIT taxonomy with Atlas mappings. Source-record frequency is not likelihood, severity or organisational exposure.</div></>}
 {!instrument&&!control&&!risk&&<><h3>Investigate this neighbourhood</h3><p>Select a labelled line on the map to inspect its rationale, or use Connections for the complete relationship record.</p>{['Control','Risk','Source','Concept'].map(kind=>{const rows=related.filter(a=>objectById.get(otherEnd(a,selected))?.kind===kind).slice(0,4);return rows.length?<section key={kind}><h3>{kind==='Control'?'Candidate controls':`${kind} connections`}</h3>{rows.map(a=><button className="related-object" key={a.id} onClick={()=>onSelect(otherEnd(a,selected))}><span><small>{a.predicate.replaceAll('-',' ')} · {basisLabel[a.basis]}</small><strong>{objectById.get(otherEnd(a,selected))?.name}</strong></span><ArrowRight/></button>)}</section>:null})}</>}
 </>}
 {tab==='Connections'&&<><p className="subtle">{related.length} recorded assertions under the active basis filter. Direction is preserved.</p>{related.map(a=><button className="assertion-row" key={a.id} onClick={()=>onEdge(a.id)}><span className={`basis-pill ${a.basis}`}>{basisLabel[a.basis]}</span><strong>{objectById.get(a.sourceNodeId)?.name}</strong><small>→ {a.predicate.replaceAll('-',' ')} →</small><strong>{objectById.get(a.targetNodeId)?.name}</strong><p>{a.rationale}</p><span>Inspect relationship <ArrowRight/></span></button>)}{!related.length&&<p>No relationships recorded under this filter. This does not establish absence of a relationship.</p>}</>}
 {tab==='Sources'&&<>{related.filter(a=>a.citations.length>0).map(a=><details key={a.id}><summary>{a.predicate.replaceAll('-',' ')} · {objectById.get(otherEnd(a,selected))?.name}</summary><span className={`basis-pill ${a.basis}`}>{basisLabel[a.basis]}</span><CitationList edge={a}/></details>)}{!related.some(a=>a.citations.length)&&<p>No source-bearing assertions are recorded under this filter.</p>}</>}
 </>}
 </aside>
}
