import { describe,it,expect } from 'vitest'
import {blankProfile,createWorkspace,readWorkspace,revise,exportFramework,exportRegister,unresolved} from './model'
import {applySuggestion,validateSuggestion} from './ai'
import {parseDraftRequest,generateDraft,grounding} from '../../server/framework-ai'
const make=()=>createWorkspace({...blankProfile,name:'Example Ltd',description:'Internal document assistant',uses:['Staff productivity']})
const suggestion=(w=make())=>({overview:'Proposed framework',assumptions:['Scope needs review'],openQuestions:['Who approves?'],practices:[{controlId:w.practices.find(p=>p.included)!.id,objective:'Proposed objective',actions:['Review access'],evidence:['Request access records'],sourceIds:[w.sourceIds[0]]}],policyQuestions:[]})
describe('Organisation framework',()=>{
 it('round trips the initial framework and accepts it as an AI request',()=>{const w=make();expect(readWorkspace(JSON.stringify(w))).toEqual(w);expect(parseDraftRequest({consent:true,workspace:w})).toEqual(w);expect(w.risks.some(r=>!r.included)).toBe(true);expect(w.practices.some(p=>p.included)).toBe(true)})
 it('preserves approved snapshots after edits and exports exclusions',()=>{const w=make();w.approval={by:'Reviewer',at:'2026-09-11',revision:1,content:exportFramework(w)};const next=revise(w,{overview:'New purpose'});expect(next.approval?.content).toContain(w.overview);expect(exportFramework(next)).toContain('Subsequent edits are unapproved');expect(exportFramework(next)).toContain('Excluded / pending review');expect(unresolved(next).length).toBeGreaterThan(0)})
 it('neutralises spreadsheet formulas',()=>{const w=make();w.practices[0].owner='=IMPORTXML("url")';expect(exportRegister(w)).toContain("'=IMPORTXML")})
 it('rejects invalid references in imports and AI drafts',()=>{const w=make();expect(()=>readWorkspace(JSON.stringify({...w,sourceIds:['invented']}))).toThrow();const s=suggestion(w);s.practices[0].sourceIds=['invented'];expect(()=>validateSuggestion(s,w)).toThrow();expect(()=>parseDraftRequest({consent:false,workspace:w})).toThrow()})
 it('does not apply suggestions automatically or fabricate policy excerpts',()=>{const w=make(),s=suggestion(w),before=JSON.stringify(w);validateSuggestion(s,w);expect(JSON.stringify(w)).toBe(before);expect(applySuggestion(w,s,[]).practices).toEqual(w.practices);const applied=applySuggestion(w,s,[s.practices[0].controlId]);expect(applied.practices?.find(p=>p.id===s.practices[0].controlId)?.origin).toBe('AI draft');expect(()=>validateSuggestion({...s,policyQuestions:[{excerpt:'invented',question:'Why?'}]},w)).toThrow()})
 it('grounds the request in trusted references and rejects truncated responses',async()=>{const w=make();expect(grounding(w).references.every(r=>w.sourceIds.includes(r.id))).toBe(true);await expect(generateDraft(w,'test','test',async()=>new Response(JSON.stringify({candidates:[{finishReason:'MAX_TOKENS'}]})))).rejects.toThrow('unfinished');const s=suggestion(w);const valid=await generateDraft(w,'test','test',async()=>new Response(JSON.stringify({candidates:[{finishReason:'STOP',content:{parts:[{text:JSON.stringify(s)}]}}]})));expect(valid).toEqual(s)})
})
