import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { AskPanel } from './AskPanel'

const sse = (events: [string, unknown][]) => {
  const text = events.map(([event, data]) => `event: ${event}\ndata: ${JSON.stringify(data)}\n\n`).join('')
  const bytes = new TextEncoder().encode(text)
  return new Response(new ReadableStream({ start(controller) { controller.enqueue(bytes.slice(0, 40)); controller.enqueue(bytes.slice(40)); controller.close() } }), { headers: { 'content-type': 'text/event-stream' } })
}

afterEach(() => { cleanup(); vi.unstubAllGlobals() })

describe('Ask the Atlas panel', () => {
  it('streams an answer with numbered citations and a sources list', async () => {
    const fetchMock = vi.fn(async () => sse([
      ['meta', { provider: 'gemini', model: 'gemini-test', records: [{ id: 'instrument:apra-cps-230', title: 'APRA CPS 230', kind: 'Source', draft: false }, { id: 'provision:eu-ai-act-14', title: 'EU AI Act Article 14', kind: 'Section', draft: true }] }],
      ['delta', { text: 'CPS 230 covers service providers **explicitly** [[instrument:apra-cps-230]].\n\n- Oversight appears in the EU AI Act [[provision:eu-ai-act-14]]' }],
      ['done', { cited: ['instrument:apra-cps-230', 'provision:eu-ai-act-14'], dropped: [], uncited: false, conclusiveLanguage: false }],
    ]))
    vi.stubGlobal('fetch', fetchMock)
    render(<AskPanel variant="page" />)
    fireEvent.change(screen.getByLabelText('Your question'), { target: { value: 'What about service providers?' } })
    fireEvent.click(screen.getByRole('button', { name: 'Ask' }))
    await waitFor(() => expect(screen.getByRole('link', { name: 'Source 1: APRA CPS 230' })).toHaveAttribute('href', '/library/apra-cps-230'))
    expect(screen.getByRole('link', { name: 'Source 2: EU AI Act Article 14' })).toHaveAttribute('href', '/library/eu-ai-act#section-eu-ai-act-14')
    expect(screen.getByText('explicitly').tagName).toBe('STRONG')
    expect(screen.getByRole('button', { name: /Show in Universe/ })).toBeInTheDocument()
    expect(screen.getByText(/generated by gemini-test from 2 retrieved Atlas records/)).toBeInTheDocument()
    expect(JSON.parse((fetchMock.mock.calls[0] as unknown as [string, RequestInit])[1].body as string)).toEqual({ question: 'What about service providers?', history: [] })
  })
  it('shows service errors without crashing', async () => {
    vi.stubGlobal('fetch', vi.fn(async () => new Response(JSON.stringify({ error: 'Ask the Atlas is resting for today.' }), { status: 503 })))
    render(<AskPanel variant="page" />)
    fireEvent.click(screen.getByRole('button', { name: /board ask about agentic AI/ }))
    await waitFor(() => expect(screen.getByRole('alert')).toHaveTextContent('resting for today'))
  })
})
