import { ArrowClockwise, ArrowUp, Planet, ShieldWarning, Sparkle, Stop } from '@phosphor-icons/react'
import { useEffect, useRef, useState } from 'react'
import { Link, navigate } from '../app/router'
import { DraftBadge } from '../ui/Kit'
import { Answer, citationOrder } from './Answer'
import { recordLink } from './links'
import { useAsk, type AskMessage } from './useAsk'
import styles from './Ask.module.css'

export const suggestions = [
  'What does APRA expect when a regulated entity uses AI?',
  'How do EU AI Act human-oversight duties compare with ISO/IEC 42001?',
  'Which controls help with CPS 230 service-provider requirements for AI vendors?',
  'What is the difference between ISO/IEC 42001 certification and ISAE 3000 assurance?',
  'What should a board ask about agentic AI?',
  'What AI obligations take effect in Australia in the next 12 months?',
]

function Reply({ message, onShow }: { message: AskMessage; onShow: (ids: string[]) => void }) {
  const records = message.records ?? []
  const order = citationOrder(message.text)
  const cited = order.map((id) => records.find((record) => record.id === id)).filter((record): record is NonNullable<typeof record> => !!record)
  return (
    <article className={styles.reply} aria-busy={message.pending}>
      {message.text ? <Answer text={message.text} records={records} /> : message.pending && <p className={styles.thinking}><Sparkle size={16} weight="fill" /> Reading {records.length || ''} Atlas records…</p>}
      {message.error && <p className={styles.error} role="alert">{message.error}</p>}
      {!message.pending && message.conclusiveLanguage && <p className={styles.warning}><ShieldWarning size={16} /> This answer uses conclusive language. The Atlas cannot establish compliance, effectiveness or assurance — treat it as a prompt for review.</p>}
      {!message.pending && message.uncited && !message.error && <p className={styles.warning}><ShieldWarning size={16} /> No Atlas record was cited, so treat this answer with caution.</p>}
      {cited.length > 0 && (
        <footer className={styles.sources}>
          <div className={styles.sourcesHead}>
            <span>Sources</span>
            <button type="button" onClick={() => onShow(cited.map((record) => record.id))}><Planet size={14} /> Show in Universe</button>
          </div>
          <ol>
            {cited.map((record) => (
              <li key={record.id}><Link to={recordLink(record.id)}>{record.title}</Link> <small>{record.kind}</small>{record.draft && <DraftBadge />}</li>
            ))}
          </ol>
        </footer>
      )}
      {!message.pending && message.model && <p className={styles.provenance}>Answer generated by {message.provider === 'demo' ? 'demo mode (no model configured)' : message.model} from {records.length} retrieved Atlas records · AI-generated; check the linked sources.</p>}
    </article>
  )
}

export function AskPanel({ variant, onNavigate }: { variant: 'drawer' | 'page'; onNavigate?: () => void }) {
  const { messages, busy, ask, stop, reset } = useAsk()
  const [draft, setDraft] = useState('')
  const listRef = useRef<HTMLDivElement>(null)
  const inputRef = useRef<HTMLTextAreaElement>(null)
  useEffect(() => { inputRef.current?.focus() }, [])
  useEffect(() => { const list = listRef.current; if (list) list.scrollTop = list.scrollHeight }, [messages])
  const submit = (text = draft) => { if (!text.trim()) return; void ask(text); setDraft('') }
  const show = (ids: string[]) => { onNavigate?.(); navigate(`/universe?highlight=${ids.map(encodeURIComponent).join(',')}`) }

  return (
    <section className={`${styles.panel} ${variant === 'page' ? styles.page : styles.inDrawer}`} aria-label="Ask the Atlas">
      <div className={styles.messages} ref={listRef} aria-live="polite">
        {messages.length === 0 ? (
          <div className={styles.intro}>
            <span className={styles.orb} aria-hidden="true"><Sparkle size={26} weight="fill" /></span>
            <h2>Ask the Atlas</h2>
            <p>Answers are drawn only from the Atlas’s reviewed records, with every claim linked to its source. It will say so when the records don’t cover your question.</p>
            <ul className={styles.suggestions}>
              {suggestions.map((suggestion) => <li key={suggestion}><button type="button" onClick={() => submit(suggestion)}>{suggestion}</button></li>)}
            </ul>
          </div>
        ) : messages.map((message) => message.role === 'user' ? <p key={message.id} className={styles.question}>{message.text}</p> : <Reply key={message.id} message={message} onShow={show} />)}
      </div>
      <form className={styles.composer} onSubmit={(event) => { event.preventDefault(); submit() }}>
        <textarea ref={inputRef} rows={2} maxLength={1000} value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="Ask about laws, standards, assurance, risks or controls…" aria-label="Your question"
          onKeyDown={(event) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); submit() } }} />
        <div className={styles.composerBar}>
          <span className={styles.notice}>Public Atlas content only — don’t enter client or personal information.</span>
          {messages.length > 0 && !busy && <button type="button" className={styles.ghost} onClick={reset} aria-label="Start a new conversation"><ArrowClockwise size={16} /></button>}
          {busy ? <button type="button" className={styles.send} onClick={stop} aria-label="Stop answering"><Stop size={16} weight="fill" /></button> : <button type="submit" className={styles.send} disabled={!draft.trim()} aria-label="Ask"><ArrowUp size={16} weight="bold" /></button>}
        </div>
      </form>
      {variant === 'drawer' && <p className={styles.more}><Link to="/ask" onClick={onNavigate}>Open full page</Link></p>}
    </section>
  )
}
